/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => NotebookLMBridgePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var http = __toESM(require("http"));
var url = __toESM(require("url"));
var NOTEBOOKLM_VIEW_TYPE = "notebooklm-webview";
var DEFAULT_SETTINGS = {
  serverPort: 27123,
  autoStart: true,
  includeMetadata: true,
  includeFrontmatter: false
};
var NotebookLMBridgePlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.server = null;
    this.isServerRunning = false;
    this.noteQueue = /* @__PURE__ */ new Map();
    this.currentPageState = null;
  }
  async onload() {
    await this.loadSettings();
    this.registerView(
      NOTEBOOKLM_VIEW_TYPE,
      (leaf) => new NotebookLMView(leaf, this)
    );
    this.statusBarItem = this.addStatusBarItem();
    this.updateStatusBar();
    this.addRibbonIcon("send", "NotebookLM\uC5D0 \uC804\uC1A1", async () => {
      await this.sendCurrentNoteToQueue();
    });
    this.addRibbonIcon("book-open", "NotebookLM \uC5F4\uAE30", async () => {
      await this.openNotebookLMView();
    });
    this.addCommand({
      id: "send-to-notebooklm",
      name: "\uD604\uC7AC \uB178\uD2B8\uB97C NotebookLM\uC5D0 \uC804\uC1A1",
      editorCallback: async (editor, view) => {
        await this.sendCurrentNoteToQueue();
      }
    });
    this.addCommand({
      id: "send-selection-to-notebooklm",
      name: "\uC120\uD0DD\uB41C \uD14D\uC2A4\uD2B8\uB97C NotebookLM\uC5D0 \uC804\uC1A1",
      editorCallback: async (editor, view) => {
        var _a;
        const selection = editor.getSelection();
        if (selection) {
          await this.sendTextToQueue(selection, ((_a = view.file) == null ? void 0 : _a.basename) || "Selection");
        } else {
          new import_obsidian.Notice("\uD14D\uC2A4\uD2B8\uB97C \uC120\uD0DD\uD574\uC8FC\uC138\uC694");
        }
      }
    });
    this.addCommand({
      id: "toggle-server",
      name: "\uBE0C\uB9BF\uC9C0 \uC11C\uBC84 \uC2DC\uC791/\uC911\uC9C0",
      callback: async () => {
        if (this.isServerRunning) {
          await this.stopServer();
        } else {
          await this.startServer();
        }
      }
    });
    this.addCommand({
      id: "clear-queue",
      name: "\uC804\uC1A1 \uB300\uAE30\uC5F4 \uBE44\uC6B0\uAE30",
      callback: () => {
        this.noteQueue.clear();
        new import_obsidian.Notice("\uB300\uAE30\uC5F4\uC774 \uBE44\uC6CC\uC84C\uC2B5\uB2C8\uB2E4");
      }
    });
    this.addCommand({
      id: "open-notebooklm",
      name: "NotebookLM \uC5F4\uAE30",
      callback: async () => {
        await this.openNotebookLMView();
      }
    });
    this.addCommand({
      id: "debug-webview-dom",
      name: "[DEBUG] NotebookLM \uD398\uC774\uC9C0 DOM \uC815\uBCF4 \uC218\uC9D1",
      callback: async () => {
        await this.debugWebviewDOM();
      }
    });
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        if (file instanceof import_obsidian.TFile && file.extension === "md") {
          menu.addItem((item) => {
            item.setTitle("NotebookLM\uC5D0 \uC804\uC1A1").setIcon("send").onClick(async () => {
              await this.sendFileToQueue(file);
            });
          });
        }
      })
    );
    this.registerEvent(
      this.app.workspace.on("editor-menu", (menu, editor, view) => {
        const selection = editor.getSelection();
        if (selection) {
          menu.addItem((item) => {
            item.setTitle("\uC120\uD0DD \uC601\uC5ED\uC744 NotebookLM\uC5D0 \uC804\uC1A1").setIcon("send").onClick(async () => {
              var _a;
              await this.sendTextToQueue(selection, ((_a = view.file) == null ? void 0 : _a.basename) || "Selection");
            });
          });
        }
      })
    );
    this.addSettingTab(new NotebookLMBridgeSettingTab(this.app, this));
    if (this.settings.autoStart) {
      await this.startServer();
    }
  }
  async onunload() {
    await this.stopServer();
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  updateStatusBar() {
    if (this.isServerRunning) {
      this.statusBarItem.setText(`\u{1F7E2} NLM Bridge :${this.settings.serverPort}`);
      this.statusBarItem.setAttribute("title", `NotebookLM Bridge \uC11C\uBC84 \uC2E4\uD589 \uC911 (\uD3EC\uD2B8: ${this.settings.serverPort})
\uB300\uAE30\uC5F4: ${this.noteQueue.size}\uAC1C`);
    } else {
      this.statusBarItem.setText("\u{1F534} NLM Bridge");
      this.statusBarItem.setAttribute("title", "NotebookLM Bridge \uC11C\uBC84 \uC911\uC9C0\uB428");
    }
  }
  async startServer() {
    if (this.isServerRunning) {
      new import_obsidian.Notice("\uC11C\uBC84\uAC00 \uC774\uBBF8 \uC2E4\uD589 \uC911\uC785\uB2C8\uB2E4");
      return;
    }
    try {
      this.server = http.createServer(async (req, res) => {
        res.setHeader("Access-Control-Allow-Origin", "*");
        res.setHeader("Access-Control-Allow-Methods", "GET, POST, DELETE, OPTIONS");
        res.setHeader("Access-Control-Allow-Headers", "Content-Type");
        res.setHeader("Content-Type", "application/json; charset=utf-8");
        if (req.method === "OPTIONS") {
          res.writeHead(200);
          res.end();
          return;
        }
        const parsedUrl = url.parse(req.url || "", true);
        const pathname = parsedUrl.pathname;
        try {
          if (pathname === "/status" && req.method === "GET") {
            res.writeHead(200);
            res.end(JSON.stringify({
              status: "running",
              version: "1.0.0",
              queueSize: this.noteQueue.size
            }));
            return;
          }
          if (pathname === "/current-note" && req.method === "GET") {
            const note = await this.getCurrentNote();
            if (note) {
              res.writeHead(200);
              res.end(JSON.stringify(note));
            } else {
              res.writeHead(404);
              res.end(JSON.stringify({ error: "\uD65C\uC131 \uB178\uD2B8\uAC00 \uC5C6\uC2B5\uB2C8\uB2E4" }));
            }
            return;
          }
          if (pathname === "/queue" && req.method === "GET") {
            const queue = Array.from(this.noteQueue.values()).filter((item) => item.status === "pending");
            res.writeHead(200);
            res.end(JSON.stringify({ notes: queue }));
            return;
          }
          if (pathname === "/queue/pop" && req.method === "POST") {
            const pendingNotes = Array.from(this.noteQueue.entries()).filter(([, item]) => item.status === "pending");
            if (pendingNotes.length > 0) {
              const [id, item] = pendingNotes[0];
              item.status = "sent";
              this.noteQueue.delete(id);
              this.updateStatusBar();
              res.writeHead(200);
              res.end(JSON.stringify(item));
            } else {
              res.writeHead(404);
              res.end(JSON.stringify({ error: "\uB300\uAE30 \uC911\uC778 \uB178\uD2B8\uAC00 \uC5C6\uC2B5\uB2C8\uB2E4" }));
            }
            return;
          }
          if ((pathname == null ? void 0 : pathname.startsWith("/queue/complete/")) && req.method === "POST") {
            const noteId = pathname.replace("/queue/complete/", "");
            if (this.noteQueue.has(noteId)) {
              this.noteQueue.delete(noteId);
              this.updateStatusBar();
              res.writeHead(200);
              res.end(JSON.stringify({ success: true }));
            } else {
              res.writeHead(404);
              res.end(JSON.stringify({ error: "\uB178\uD2B8\uB97C \uCC3E\uC744 \uC218 \uC5C6\uC2B5\uB2C8\uB2E4" }));
            }
            return;
          }
          if (pathname === "/queue/clear" && req.method === "DELETE") {
            this.noteQueue.clear();
            this.updateStatusBar();
            res.writeHead(200);
            res.end(JSON.stringify({ success: true }));
            return;
          }
          if (pathname === "/notes" && req.method === "GET") {
            const files = this.app.vault.getMarkdownFiles();
            const notes = files.slice(0, 100).map((file) => ({
              title: file.basename,
              path: file.path
            }));
            res.writeHead(200);
            res.end(JSON.stringify({ notes }));
            return;
          }
          if ((pathname == null ? void 0 : pathname.startsWith("/note/")) && req.method === "GET") {
            const notePath = decodeURIComponent(pathname.replace("/note/", ""));
            const file = this.app.vault.getAbstractFileByPath(notePath);
            if (file instanceof import_obsidian.TFile) {
              const note = await this.getFileContent(file);
              res.writeHead(200);
              res.end(JSON.stringify(note));
            } else {
              res.writeHead(404);
              res.end(JSON.stringify({ error: "\uB178\uD2B8\uB97C \uCC3E\uC744 \uC218 \uC5C6\uC2B5\uB2C8\uB2E4" }));
            }
            return;
          }
          res.writeHead(404);
          res.end(JSON.stringify({ error: "Not found" }));
        } catch (error) {
          console.error("Server error:", error);
          res.writeHead(500);
          res.end(JSON.stringify({ error: "Internal server error" }));
        }
      });
      this.server.listen(this.settings.serverPort, "127.0.0.1", () => {
        this.isServerRunning = true;
        this.updateStatusBar();
        new import_obsidian.Notice(`NotebookLM Bridge \uC11C\uBC84 \uC2DC\uC791 (\uD3EC\uD2B8: ${this.settings.serverPort})`);
      });
      this.server.on("error", (error) => {
        if (error.code === "EADDRINUSE") {
          new import_obsidian.Notice(`\uD3EC\uD2B8 ${this.settings.serverPort}\uAC00 \uC774\uBBF8 \uC0AC\uC6A9 \uC911\uC785\uB2C8\uB2E4`);
        } else {
          new import_obsidian.Notice(`\uC11C\uBC84 \uC624\uB958: ${error.message}`);
        }
        this.isServerRunning = false;
        this.updateStatusBar();
      });
    } catch (error) {
      console.error("Failed to start server:", error);
      new import_obsidian.Notice("\uC11C\uBC84 \uC2DC\uC791 \uC2E4\uD328");
    }
  }
  async stopServer() {
    if (this.server) {
      return new Promise((resolve) => {
        var _a;
        (_a = this.server) == null ? void 0 : _a.close(() => {
          this.server = null;
          this.isServerRunning = false;
          this.updateStatusBar();
          new import_obsidian.Notice("NotebookLM Bridge \uC11C\uBC84 \uC911\uC9C0");
          resolve();
        });
      });
    }
  }
  // NotebookLM 웹뷰 열기
  async openNotebookLMView() {
    const existing = this.app.workspace.getLeavesOfType(NOTEBOOKLM_VIEW_TYPE);
    if (existing.length > 0) {
      this.app.workspace.revealLeaf(existing[0]);
    } else {
      const leaf = this.app.workspace.getRightLeaf(false);
      if (leaf) {
        await leaf.setViewState({
          type: NOTEBOOKLM_VIEW_TYPE,
          active: true
        });
        this.app.workspace.revealLeaf(leaf);
      }
    }
  }
  // NotebookLM 웹뷰 가져오기
  getNotebookLMView() {
    const leaves = this.app.workspace.getLeavesOfType(NOTEBOOKLM_VIEW_TYPE);
    if (leaves.length > 0) {
      return leaves[0].view;
    }
    return null;
  }
  async getCurrentNote() {
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (!activeView || !activeView.file) {
      return null;
    }
    return await this.getFileContent(activeView.file);
  }
  async getFileContent(file) {
    var _a, _b;
    let content = await this.app.vault.read(file);
    const cache = this.app.metadataCache.getFileCache(file);
    let shareLink;
    if ((_a = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _a.share_link) {
      shareLink = cache.frontmatter.share_link;
    }
    if (!this.settings.includeFrontmatter) {
      content = content.replace(/^---\n[\s\S]*?\n---\n/, "");
    }
    const note = {
      title: file.basename,
      content: content.trim(),
      path: file.path,
      shareLink
    };
    if (this.settings.includeMetadata) {
      note.metadata = {
        created: file.stat.ctime,
        modified: file.stat.mtime,
        tags: ((_b = cache == null ? void 0 : cache.tags) == null ? void 0 : _b.map((t) => t.tag)) || []
      };
    }
    return note;
  }
  async sendCurrentNoteToQueue() {
    new import_obsidian.Notice("\uC804\uC1A1 \uBC84\uD2BC \uD074\uB9AD\uB428!");
    const note = await this.getCurrentNote();
    if (!note) {
      new import_obsidian.Notice("\uD65C\uC131 \uB178\uD2B8\uAC00 \uC5C6\uC2B5\uB2C8\uB2E4");
      return;
    }
    new import_obsidian.Notice(`\uB178\uD2B8: ${note.title} - \uBAA8\uB2EC \uC5F4\uAE30 \uC2DC\uB3C4`);
    const notebooks = [];
    const modal = new NotebookSelectModal(this.app, this, notebooks, note.title, async (selected) => {
      if (selected) {
        new import_obsidian.Notice(`\uC120\uD0DD: ${selected.title}`);
      } else {
        new import_obsidian.Notice("\uC0C8 \uB178\uD2B8\uBD81 \uB9CC\uB4E4\uAE30 \uC120\uD0DD\uB428");
      }
      this.addToQueue(note);
      await this.openNotebookLMView();
    });
    modal.open();
  }
  // 노트북 선택 모달 표시
  async showNotebookSelectModal(note) {
    console.log("[NotebookLM Bridge] \uBAA8\uB2EC \uD45C\uC2DC \uC2DC\uC791");
    let notebooks = [];
    const view = this.getNotebookLMView();
    if (view && view.webview) {
      try {
        const result = await view.webview.executeJavaScript(`
					(function() {
						const notebooks = [];
						document.querySelectorAll('a[href*="/notebook/"]').forEach(el => {
							const href = el.getAttribute('href');
							const match = href.match(/\\/notebook\\/([^/]+)/);
							if (match) {
								let title = el.textContent.trim();
								if (!title || title.length > 100) {
									const titleEl = el.querySelector('[class*="title"], h2, h3, span');
									if (titleEl) title = titleEl.textContent.trim();
								}
								if (title && !notebooks.find(n => n.id === match[1])) {
									notebooks.push({
										id: match[1],
										title: title || 'Untitled',
										url: 'https://notebooklm.google.com' + href
									});
								}
							}
						});
						return notebooks;
					})();
				`);
        notebooks = result || [];
        console.log("[NotebookLM Bridge] \uB178\uD2B8\uBD81 \uBAA9\uB85D:", notebooks);
      } catch (error) {
        console.error("[NotebookLM Bridge] \uB178\uD2B8\uBD81 \uBAA9\uB85D \uAC00\uC838\uC624\uAE30 \uC2E4\uD328:", error);
      }
    }
    console.log("[NotebookLM Bridge] \uBAA8\uB2EC \uC0DD\uC131");
    const modal = new NotebookSelectModal(this.app, this, notebooks, note.title, async (selectedNotebook) => {
      await this.openNotebookLMView();
      const nlmView = this.getNotebookLMView();
      if (selectedNotebook) {
        new import_obsidian.Notice(`"${selectedNotebook.title}" \uB178\uD2B8\uBD81\uC73C\uB85C \uC774\uB3D9 \uC911...`);
        if (nlmView && nlmView.webview) {
          nlmView.webview.loadURL(selectedNotebook.url);
          this.addToQueue(note);
          setTimeout(() => {
            nlmView.addFromQueue();
          }, 3e3);
        } else {
          this.addToQueue(note);
        }
      } else {
        new import_obsidian.Notice("NotebookLM\uC5D0\uC11C \uC0C8 \uB178\uD2B8\uBD81\uC744 \uB9CC\uB4E4\uC5B4\uC8FC\uC138\uC694.\n\uB178\uD2B8\uAC00 \uB300\uAE30\uC5F4\uC5D0 \uCD94\uAC00\uB418\uC5C8\uC2B5\uB2C8\uB2E4.");
        this.addToQueue(note);
        if (nlmView && nlmView.webview) {
          nlmView.webview.loadURL("https://notebooklm.google.com");
        }
      }
    });
    modal.open();
  }
  async sendFileToQueue(file) {
    const note = await this.getFileContent(file);
    await this.openNotebookLMView();
    const view = this.getNotebookLMView();
    if (view && view.webview) {
      new import_obsidian.Notice("\uB178\uD2B8\uBD81 \uBAA9\uB85D\uC744 \uAC00\uC838\uC624\uB294 \uC911...");
      view.webview.loadURL("https://notebooklm.google.com");
      setTimeout(async () => {
        const notebooks = await this.getNotebooksFromWebview();
        console.log("[NotebookLM Bridge] Found notebooks:", notebooks);
        this.showNotebookModal(note, notebooks);
      }, 3e3);
    } else {
      this.showNotebookModal(note, []);
    }
  }
  // 웹뷰에서 노트북 목록 가져오기
  async getNotebooksFromWebview() {
    const view = this.getNotebookLMView();
    if (!view || !view.webview) {
      return [];
    }
    try {
      const result = await view.webview.executeJavaScript(`
				(function() {
					const notebooks = [];
					const seen = new Set();

					// \uBC29\uBC95 1: project-table\uC5D0\uC11C \uB178\uD2B8\uBD81 \uC81C\uBAA9 \uAC00\uC838\uC624\uAE30 (\uBAA8\uBC14\uC77C/\uC881\uC740 \uD654\uBA74)
					const table = document.querySelector('table.project-table');
					if (table) {
						const rows = table.querySelectorAll('tbody tr, tr');
						rows.forEach((row, index) => {
							const titleEl = row.querySelector('.project-table-title, [class*="table-title"]');
							if (titleEl) {
								const title = titleEl.textContent.trim();
								if (title && !seen.has(title)) {
									seen.add(title);
									notebooks.push({
										id: 'row-' + index,
										title: title,
										url: '',
										rowIndex: index,
										viewType: 'table'
									});
								}
							}
						});
					}

					// \uBC29\uBC95 2: PC \uBDF0 \uCE74\uB4DC \uB808\uC774\uC544\uC6C3 - project-button \uC694\uC18C (\uB113\uC740 \uD654\uBA74)
					if (notebooks.length === 0) {
						// project-button \uC694\uC18C\uB4E4 \uCC3E\uAE30 (PC \uCE74\uB4DC \uBDF0\uC758 \uBA54\uC778 \uCEE8\uD14C\uC774\uB108)
						const projectButtons = document.querySelectorAll('project-button.project-button');
						projectButtons.forEach((btn, index) => {
							// span.project-button-title\uC5D0\uC11C \uC81C\uBAA9 \uCD94\uCD9C
							const titleEl = btn.querySelector('span.project-button-title, .project-button-title');
							if (titleEl) {
								const title = titleEl.textContent.trim();
								if (title && !seen.has(title) && !title.includes('\uC0C8 \uB178\uD2B8') && !title.includes('\uB9CC\uB4E4\uAE30')) {
									seen.add(title);
									notebooks.push({
										id: 'projectbtn-' + index,
										title: title,
										url: '',
										cardIndex: index,
										viewType: 'projectButton'
									});
								}
							}
						});
					}

					// \uBC29\uBC95 3: mat-card.project-button-card \uCC3E\uAE30
					if (notebooks.length === 0) {
						const matCards = document.querySelectorAll('mat-card.project-button-card');
						matCards.forEach((card, index) => {
							const titleEl = card.querySelector('span.project-button-title, .project-button-title');
							if (titleEl) {
								const title = titleEl.textContent.trim();
								if (title && !seen.has(title) && !title.includes('\uC0C8 \uB178\uD2B8') && !title.includes('\uB9CC\uB4E4\uAE30')) {
									seen.add(title);
									notebooks.push({
										id: 'matcard-' + index,
										title: title,
										url: '',
										cardIndex: index,
										viewType: 'matcard'
									});
								}
							}
						});
					}

					// \uBC29\uBC95 4: \uD074\uB9AD \uAC00\uB2A5\uD55C \uB178\uD2B8\uBD81 \uD56D\uBAA9 (href \uD3EC\uD568)
					if (notebooks.length === 0) {
						document.querySelectorAll('a[href*="/notebook/"]').forEach(el => {
							const href = el.getAttribute('href') || '';
							const match = href.match(/\\/notebook\\/([^/\\?]+)/);
							if (match && !seen.has(match[1])) {
								seen.add(match[1]);
								const title = el.textContent.trim() || 'Untitled notebook';
								// "\uC0C8 \uB178\uD2B8 \uB9CC\uB4E4\uAE30" \uC81C\uC678
								if (!title.includes('\uC0C8 \uB178\uD2B8') && !title.includes('\uB9CC\uB4E4\uAE30')) {
									notebooks.push({
										id: match[1],
										title: title,
										url: 'https://notebooklm.google.com' + href,
										viewType: 'link'
									});
								}
							}
						});
					}

					// \uBC29\uBC95 5: \uC81C\uBAA9 \uD14D\uC2A4\uD2B8 \uAE30\uBC18 \uAC80\uC0C9 (\uCD5C\uD6C4\uC758 \uBC29\uBC95)
					if (notebooks.length === 0) {
						// "\uB0B4 \uB178\uD2B8\uBD81" \uC139\uC158 \uCC3E\uAE30
						const sections = document.querySelectorAll('[class*="section"], [class*="content"], main');
						sections.forEach(section => {
							const items = section.querySelectorAll('[role="button"], [role="listitem"], [class*="clickable"]');
							items.forEach((item, index) => {
								const text = item.textContent.trim();
								// \uB0A0\uC9DC \uD328\uD134\uC774 \uD3EC\uD568\uB41C \uD56D\uBAA9\uC740 \uB178\uD2B8\uBD81\uC77C \uAC00\uB2A5\uC131 \uB192\uC74C
								if (text && text.match(/\\d{4}.*\\d{1,2}.*\\d{1,2}/) && !seen.has(text.substring(0, 50))) {
									// \uCCAB \uC904\uB9CC \uC81C\uBAA9\uC73C\uB85C \uC0AC\uC6A9
									const lines = text.split('\\n');
									const title = lines[0].trim();
									if (title && !title.includes('\uC0C8 \uB178\uD2B8') && !title.includes('\uB9CC\uB4E4\uAE30')) {
										seen.add(title);
										notebooks.push({
											id: 'item-' + index,
											title: title,
											url: '',
											itemIndex: index,
											viewType: 'item'
										});
									}
								}
							});
						});
					}

					console.log('[Bridge] Found notebooks:', notebooks, 'View type:', notebooks[0]?.viewType);
					return notebooks;
				})();
			`);
      return result || [];
    } catch (error) {
      console.error("[NotebookLM Bridge] Failed to get notebooks:", error);
      return [];
    }
  }
  // 노트북 선택 모달 표시
  showNotebookModal(note, notebooks) {
    const modal = new NotebookSelectModal(this.app, this, notebooks, note.title, async (selected) => {
      const view = this.getNotebookLMView();
      if (selected) {
        new import_obsidian.Notice(`"${selected.title}" \uB178\uD2B8\uBD81\uC73C\uB85C \uC774\uB3D9 \uC911...`);
        if (view && view.webview) {
          if (selected.url) {
            view.webview.loadURL(selected.url);
          } else {
            await view.webview.executeJavaScript(`
							(function() {
								const title = ${JSON.stringify(selected.title)};
								const viewType = ${JSON.stringify(selected.viewType || "table")};

								// \uBC29\uBC95 1: \uD14C\uC774\uBE14 \uD589 \uD074\uB9AD (\uBAA8\uBC14\uC77C \uBDF0)
								if (viewType === 'table') {
									const titleEls = document.querySelectorAll('.project-table-title');
									for (const el of titleEls) {
										if (el.textContent.trim() === title) {
											const row = el.closest('tr');
											if (row) {
												row.click();
												console.log('[Bridge] Clicked table row for:', title);
												return { success: true, method: 'table' };
											}
										}
									}
								}

								// \uBC29\uBC95 2: project-button \uD074\uB9AD (PC \uBDF0 \uCE74\uB4DC)
								if (viewType === 'projectButton') {
									const projectButtons = document.querySelectorAll('project-button.project-button');
									for (const btn of projectButtons) {
										const titleEl = btn.querySelector('span.project-button-title, .project-button-title');
										if (titleEl && titleEl.textContent.trim() === title) {
											// mat-card \uB610\uB294 primary-action-button \uD074\uB9AD
											const clickTarget = btn.querySelector('.primary-action-button, mat-card.project-button-card') || btn;
											clickTarget.click();
											console.log('[Bridge] Clicked project-button for:', title);
											return { success: true, method: 'projectButton' };
										}
									}
								}

								// \uBC29\uBC95 3: mat-card \uD074\uB9AD (PC \uBDF0)
								if (viewType === 'matcard') {
									const matCards = document.querySelectorAll('mat-card.project-button-card');
									for (const card of matCards) {
										const titleEl = card.querySelector('span.project-button-title, .project-button-title');
										if (titleEl && titleEl.textContent.trim() === title) {
											const clickTarget = card.querySelector('.primary-action-button') || card;
											clickTarget.click();
											console.log('[Bridge] Clicked mat-card for:', title);
											return { success: true, method: 'matcard' };
										}
									}
								}

								// \uBC29\uBC95 4: \uC81C\uBAA9 \uD14D\uC2A4\uD2B8\uB85C \uD074\uB9AD \uAC00\uB2A5\uD55C \uC694\uC18C \uCC3E\uAE30 (\uD3F4\uBC31)
								const allElements = document.querySelectorAll('*');
								for (const el of allElements) {
									if (el.textContent.trim() === title &&
										(el.tagName === 'H2' || el.tagName === 'H3' ||
										 el.className.includes('title') || el.closest('[role="button"]'))) {
										// \uD074\uB9AD \uAC00\uB2A5\uD55C \uBD80\uBAA8 \uCC3E\uAE30
										const clickable = el.closest('[role="button"], a, button, [class*="card"], [class*="item"], tr') || el;
										clickable.click();
										console.log('[Bridge] Clicked element for:', title, clickable.tagName);
										return { success: true, method: 'fallback' };
									}
								}

								return { success: false, error: 'Notebook not found: ' + title };
							})();
						`);
          }
          setTimeout(() => {
            this.addSourceToNotebook(view, note);
          }, 3e3);
        }
      } else {
        new import_obsidian.Notice("\uC0C8 \uB178\uD2B8\uBD81 \uC0DD\uC131 \uC911...");
        if (view && view.webview) {
          await view.webview.executeJavaScript(`
						(function() {
							const buttons = document.querySelectorAll('button');
							for (const btn of buttons) {
								const text = (btn.textContent || '').toLowerCase();
								if (text.includes('\uB9CC\uB4E4\uAE30') || text.includes('create')) {
									btn.click();
									console.log('[Bridge] Clicked create notebook button');
									return true;
								}
							}
							return false;
						})();
					`);
          setTimeout(() => {
            this.addSourceToNotebook(view, note);
          }, 3e3);
        }
      }
    });
    modal.open();
  }
  // 새 노트북 생성 후 소스 추가
  async createNewNotebookAndAddSource(view, note) {
    if (!view.webview)
      return;
    try {
      await view.webview.executeJavaScript(`
				(async function() {
					// "+ \uB9CC\uB4E4\uAE30" \uBC84\uD2BC \uCC3E\uAE30
					const createBtnSelectors = [
						'button:has-text("\uB9CC\uB4E4\uAE30")',
						'button:has-text("Create")',
						'button[aria-label*="Create"]',
						'button[aria-label*="\uB9CC\uB4E4\uAE30"]',
						'[class*="create"] button',
						'button[class*="create"]'
					];

					let createBtn = null;

					// \uBC84\uD2BC \uD14D\uC2A4\uD2B8\uB85C \uCC3E\uAE30
					const allButtons = document.querySelectorAll('button');
					for (const btn of allButtons) {
						const text = btn.textContent.toLowerCase();
						if (text.includes('\uB9CC\uB4E4\uAE30') || text.includes('create') || text.includes('new')) {
							createBtn = btn;
							break;
						}
					}

					if (createBtn) {
						createBtn.click();
						console.log('[Obsidian Bridge] Create button clicked');
						return { success: true, action: 'clicked_create' };
					}

					return { success: false, error: 'Create button not found' };
				})();
			`);
      new import_obsidian.Notice("\uC0C8 \uB178\uD2B8\uBD81\uC774 \uC0DD\uC131\uB418\uBA74 \uC18C\uC2A4\uAC00 \uC790\uB3D9 \uCD94\uAC00\uB429\uB2C8\uB2E4.\n\uC7A0\uC2DC \uAE30\uB2E4\uB824\uC8FC\uC138\uC694...");
      setTimeout(() => {
        this.addSourceToNotebook(view, note);
      }, 4e3);
    } catch (error) {
      console.error("[NotebookLM Bridge] Create notebook failed:", error);
      new import_obsidian.Notice("\uC0C8 \uB178\uD2B8\uBD81 \uC0DD\uC131\uC5D0 \uC2E4\uD328\uD588\uC2B5\uB2C8\uB2E4. \uC218\uB3D9\uC73C\uB85C \uC0DD\uC131\uD574\uC8FC\uC138\uC694.");
      this.addToQueue(note);
    }
  }
  // 노트북에 소스 추가 (완전 자동화)
  async addSourceToNotebook(view, note) {
    if (!view.webview)
      return;
    if (note.shareLink) {
      new import_obsidian.Notice(`"${note.title}" \uB9C1\uD06C \uC18C\uC2A4 \uCD94\uAC00 \uC911...`);
      await this.addLinkSourceToNotebook(view, note);
      return;
    }
    const content = "# " + note.title + "\n\n" + note.content;
    new import_obsidian.Notice(`"${note.title}" \uD14D\uC2A4\uD2B8 \uC18C\uC2A4 \uCD94\uAC00 \uC911...`);
    try {
      await view.webview.executeJavaScript(`
				(function() {
					// \uD0ED \uBC84\uD2BC \uCC3E\uAE30 (\uCD9C\uCC98, Sources, \uC18C\uC2A4)
					const tabs = document.querySelectorAll('[role="tab"], button[class*="tab"], mat-tab-header button, .mat-mdc-tab');
					for (const tab of tabs) {
						const text = (tab.textContent || '').trim().toLowerCase();
						if (text.includes('\uCD9C\uCC98') || text.includes('sources') || text.includes('\uC18C\uC2A4')) {
							tab.click();
							console.log('[Bridge] Switched to Sources tab');
							return { success: true, tab: text };
						}
					}

					// \uB124\uBE44\uAC8C\uC774\uC158 \uBC14\uC5D0\uC11C \uCC3E\uAE30
					const navItems = document.querySelectorAll('nav button, nav a, [class*="nav"] button');
					for (const item of navItems) {
						const text = (item.textContent || '').trim().toLowerCase();
						if (text.includes('\uCD9C\uCC98') || text.includes('sources') || text.includes('\uC18C\uC2A4')) {
							item.click();
							console.log('[Bridge] Clicked nav item:', text);
							return { success: true, nav: text };
						}
					}

					// bottom-nav\uB098 tab-bar \uD615\uD0DC\uC77C \uC218 \uC788\uC74C
					const bottomNav = document.querySelectorAll('[class*="bottom-nav"] *, [class*="tab-bar"] *');
					for (const item of bottomNav) {
						const text = (item.textContent || '').trim().toLowerCase();
						if (text.includes('\uCD9C\uCC98') || text.includes('sources')) {
							item.click();
							return { success: true, bottomNav: text };
						}
					}

					return { success: false, error: 'Sources tab not found (might be desktop view)' };
				})();
			`);
      await this.delay(800);
      const step1 = await view.webview.executeJavaScript(`
				(function() {
					// \uC5EC\uB7EC \uC140\uB809\uD130 \uC2DC\uB3C4
					const selectors = [
						'button.add-source-button',
						'button[aria-label="\uCD9C\uCC98 \uCD94\uAC00"]',
						'button[aria-label="\uC5C5\uB85C\uB4DC \uC18C\uC2A4 \uB300\uD654\uC0C1\uC790 \uC5F4\uAE30"]',
						'button.upload-button',
						'button.upload-icon-button'
					];

					for (const sel of selectors) {
						const btn = document.querySelector(sel);
						if (btn && !btn.disabled) {
							btn.click();
							console.log('[Bridge] Clicked:', sel);
							return { success: true, selector: sel };
						}
					}

					// \uD14D\uC2A4\uD2B8\uB85C \uCC3E\uAE30
					const buttons = document.querySelectorAll('button');
					for (const btn of buttons) {
						const text = (btn.textContent || '').trim();
						if (text.includes('\uC18C\uC2A4 \uCD94\uAC00') || text.includes('\uC18C\uC2A4 \uC5C5\uB85C\uB4DC') ||
							text === 'upload' || text.includes('Add source')) {
							btn.click();
							console.log('[Bridge] Clicked button with text:', text);
							return { success: true, text: text };
						}
					}

					return { success: false, error: 'Source add button not found' };
				})();
			`);
      console.log("[NotebookLM Bridge] Step 1 (\uC18C\uC2A4 \uCD94\uAC00 \uBC84\uD2BC):", step1);
      await this.delay(1500);
      await view.webview.executeJavaScript(`
				(function() {
					// mat-bottom-sheet-container \uB0B4\uBD80\uC758 \uC2A4\uD06C\uB864 \uAC00\uB2A5 \uC601\uC5ED \uCC3E\uAE30
					const bottomSheet = document.querySelector('mat-bottom-sheet-container');
					if (bottomSheet) {
						// bottom-sheet \uC790\uCCB4\uB97C \uC2A4\uD06C\uB864
						bottomSheet.scrollTop = bottomSheet.scrollHeight;
						console.log('[Bridge] Scrolled mat-bottom-sheet-container');
					}

					// upload-dialog-panel \uB0B4\uBD80 \uC2A4\uD06C\uB864
					const panel = document.querySelector('.upload-dialog-panel');
					if (panel) {
						panel.scrollTop = panel.scrollHeight;
						// \uD328\uB110 \uB0B4\uBD80\uC758 \uBAA8\uB4E0 \uC624\uBC84\uD50C\uB85C\uC6B0 \uAC00\uB2A5 \uC694\uC18C \uCC3E\uAE30
						const scrollables = panel.querySelectorAll('*');
						for (const el of scrollables) {
							const style = window.getComputedStyle(el);
							if (style.overflowY === 'auto' || style.overflowY === 'scroll') {
								el.scrollTop = el.scrollHeight;
								console.log('[Bridge] Scrolled inner element:', el.className);
							}
						}
					}

					// cdk-overlay-pane \uC2A4\uD06C\uB864
					const overlay = document.querySelector('.cdk-overlay-pane');
					if (overlay) {
						overlay.scrollTop = overlay.scrollHeight;
					}
				})();
			`);
      await this.delay(500);
      await view.webview.executeJavaScript(`
				(function() {
					const allElements = document.querySelectorAll('*');
					for (const el of allElements) {
						const text = (el.textContent || '').trim();
						if (text === '\uD14D\uC2A4\uD2B8 \uBD99\uC5EC\uB123\uAE30' || text === 'Paste text') {
							el.scrollIntoView({ behavior: 'smooth', block: 'center' });
							console.log('[Bridge] Scrolled to \uD14D\uC2A4\uD2B8 \uBD99\uC5EC\uB123\uAE30 via scrollIntoView');
							return;
						}
					}
					// \uBABB \uCC3E\uC73C\uBA74 "\uBCF5\uC0AC\uB41C \uD14D\uC2A4\uD2B8"\uB85C \uC2DC\uB3C4
					for (const el of allElements) {
						const text = (el.textContent || '').trim();
						if (text === '\uBCF5\uC0AC\uB41C \uD14D\uC2A4\uD2B8' || text === 'Copied text') {
							el.scrollIntoView({ behavior: 'smooth', block: 'center' });
							console.log('[Bridge] Scrolled to \uBCF5\uC0AC\uB41C \uD14D\uC2A4\uD2B8 via scrollIntoView');
							return;
						}
					}
				})();
			`);
      await this.delay(800);
      const step2 = await view.webview.executeJavaScript(`
				(function() {
					// "\uBCF5\uC0AC\uB41C \uD14D\uC2A4\uD2B8" \uC9C1\uC811 \uD074\uB9AD \uC2DC\uB3C4
					const allElements = document.querySelectorAll('*');
					for (const el of allElements) {
						const text = (el.textContent || '').trim();
						// \uC815\uD655\uD788 "\uBCF5\uC0AC\uB41C \uD14D\uC2A4\uD2B8" \uB9E4\uCE6D
						if (text === '\uBCF5\uC0AC\uB41C \uD14D\uC2A4\uD2B8' || text === 'Copied text') {
							el.click();
							console.log('[Bridge] Clicked \uBCF5\uC0AC\uB41C \uD14D\uC2A4\uD2B8:', el.tagName, el.className);
							return { success: true, clicked: text };
						}
					}

					// "\uD14D\uC2A4\uD2B8 \uBD99\uC5EC\uB123\uAE30" \uC139\uC158 \uD074\uB9AD (\uD655\uC7A5 \uD544\uC694\uD560 \uC218 \uC788\uC74C)
					for (const el of allElements) {
						const text = (el.textContent || '').trim();
						if (text === '\uD14D\uC2A4\uD2B8 \uBD99\uC5EC\uB123\uAE30' || text === 'Paste text') {
							el.click();
							console.log('[Bridge] Clicked \uD14D\uC2A4\uD2B8 \uBD99\uC5EC\uB123\uAE30:', el.tagName);
							return { success: true, clicked: text, needsSecondClick: true };
						}
					}

					return { success: false, error: 'Text paste option not found in DOM' };
				})();
			`);
      console.log("[NotebookLM Bridge] Step 2 (\uBCF5\uC0AC\uB41C \uD14D\uC2A4\uD2B8 \uC635\uC158):", step2);
      if (step2 == null ? void 0 : step2.needsSecondClick) {
        await this.delay(800);
        await view.webview.executeJavaScript(`
					(function() {
						const modal = document.querySelector('.upload-dialog-panel, mat-bottom-sheet-container, [role="dialog"]');
						if (!modal) return { success: false };
						const allElements = modal.querySelectorAll('*');
						for (const el of allElements) {
							const text = (el.textContent || '').trim();
							if (text === '\uBCF5\uC0AC\uB41C \uD14D\uC2A4\uD2B8' || text === 'Copied text') {
								el.click();
								console.log('[Bridge] Step 2.5: Clicked \uBCF5\uC0AC\uB41C \uD14D\uC2A4\uD2B8');
								return { success: true };
							}
						}
						return { success: false };
					})();
				`);
      }
      await this.delay(1500);
      const step3 = await view.webview.executeJavaScript(`
				(function() {
					const content = ${JSON.stringify(content)};

					// \uC815\uD655\uD55C \uC140\uB809\uD130: textarea.text-area
					let textarea = document.querySelector('textarea.text-area');

					// \uC5C6\uC73C\uBA74 \uB2E4\uC774\uC5BC\uB85C\uADF8 \uB0B4 textarea \uCC3E\uAE30
					if (!textarea) {
						const modal = document.querySelector('.upload-dialog-panel, [role="dialog"], mat-dialog-container');
						if (modal) {
							textarea = modal.querySelector('textarea');
						}
					}

					if (textarea && textarea.offsetParent !== null) {
						textarea.focus();
						textarea.value = content;
						// Angular/React \uB4F1\uC5D0\uC11C \uAC12 \uBCC0\uACBD \uAC10\uC9C0\uB97C \uC704\uD574 \uC5EC\uB7EC \uC774\uBCA4\uD2B8 \uBC1C\uC0DD
						textarea.dispatchEvent(new Event('input', { bubbles: true }));
						textarea.dispatchEvent(new Event('change', { bubbles: true }));
						textarea.dispatchEvent(new KeyboardEvent('keyup', { bubbles: true }));
						console.log('[Bridge] Text inserted into textarea.text-area');
						return { success: true };
					}

					return { success: false, error: 'textarea.text-area not found or not visible' };
				})();
			`);
      console.log("[NotebookLM Bridge] Step 3 (\uD14D\uC2A4\uD2B8 \uC785\uB825):", step3);
      await this.delay(800);
      const step4 = await view.webview.executeJavaScript(`
				(function() {
					const buttons = document.querySelectorAll('button');
					for (const btn of buttons) {
						const text = (btn.textContent || '').trim();
						if (text === '\uC0BD\uC785' || text === 'Insert') {
							// \uBC84\uD2BC\uC774 \uD65C\uC131\uD654\uB420 \uB54C\uAE4C\uC9C0 \uB300\uAE30
							if (!btn.disabled) {
								btn.click();
								console.log('[Bridge] Clicked \uC0BD\uC785 button');
								return { success: true };
							} else {
								return { success: false, error: '\uC0BD\uC785 button is disabled' };
							}
						}
					}
					return { success: false, error: '\uC0BD\uC785 button not found' };
				})();
			`);
      console.log("[NotebookLM Bridge] Step 4 (\uC0BD\uC785 \uBC84\uD2BC):", step4);
      if ((step3 == null ? void 0 : step3.success) && (step4 == null ? void 0 : step4.success)) {
        new import_obsidian.Notice(`\u2705 "${note.title}" \uC18C\uC2A4\uAC00 \uCD94\uAC00\uB418\uC5C8\uC2B5\uB2C8\uB2E4!`, 5e3);
      } else if (step3 == null ? void 0 : step3.success) {
        new import_obsidian.Notice(`\u{1F4DD} \uD14D\uC2A4\uD2B8 \uC785\uB825 \uC644\uB8CC!
"\uC0BD\uC785" \uBC84\uD2BC\uC744 \uD074\uB9AD\uD574\uC8FC\uC138\uC694.`, 5e3);
      } else {
        await navigator.clipboard.writeText(content);
        new import_obsidian.Notice(`\u{1F4CB} \uC790\uB3D9 \uC785\uB825 \uC2E4\uD328. \uD074\uB9BD\uBCF4\uB4DC\uC5D0 \uBCF5\uC0AC\uB428.

Cmd+V\uB85C \uBD99\uC5EC\uB123\uAE30 \uD6C4 \uC0BD\uC785 \uD074\uB9AD`, 8e3);
      }
    } catch (error) {
      console.error("[NotebookLM Bridge] Auto add source failed:", error);
      try {
        await navigator.clipboard.writeText(content);
        new import_obsidian.Notice(`\u{1F4CB} "${note.title}" \uD074\uB9BD\uBCF4\uB4DC\uC5D0 \uBCF5\uC0AC\uB428.

\uC218\uB3D9\uC73C\uB85C \uBD99\uC5EC\uB123\uAE30 \uD574\uC8FC\uC138\uC694.`, 8e3);
      } catch (e) {
        new import_obsidian.Notice("\uC18C\uC2A4 \uCD94\uAC00\uC5D0 \uC2E4\uD328\uD588\uC2B5\uB2C8\uB2E4.", 5e3);
      }
    }
  }
  // 링크 소스 추가 (share_link가 있는 노트용)
  async addLinkSourceToNotebook(view, note) {
    if (!view.webview || !note.shareLink)
      return;
    try {
      await view.webview.executeJavaScript(`
				(function() {
					const tabs = document.querySelectorAll('[role="tab"], button[class*="tab"], .mat-mdc-tab');
					for (const tab of tabs) {
						const text = (tab.textContent || '').trim().toLowerCase();
						if (text.includes('\uCD9C\uCC98') || text.includes('sources') || text.includes('\uC18C\uC2A4')) {
							tab.click();
							return { success: true, tab: text };
						}
					}
					return { success: false };
				})();
			`);
      await this.delay(800);
      const step1 = await view.webview.executeJavaScript(`
				(function() {
					const selectors = [
						'button[aria-label="\uCD9C\uCC98 \uCD94\uAC00"]',
						'button[aria-label="\uC18C\uC2A4 \uCD94\uAC00"]',
						'button.add-source-button',
						'button[aria-label="\uC5C5\uB85C\uB4DC \uC18C\uC2A4 \uB300\uD654\uC0C1\uC790 \uC5F4\uAE30"]'
					];
					for (const sel of selectors) {
						const btn = document.querySelector(sel);
						if (btn && !btn.disabled) {
							btn.click();
							return { success: true, selector: sel };
						}
					}
					// \uD14D\uC2A4\uD2B8\uB85C \uCC3E\uAE30
					const buttons = document.querySelectorAll('button');
					for (const btn of buttons) {
						const text = (btn.textContent || '').trim();
						if (text.includes('\uC18C\uC2A4 \uCD94\uAC00') || text.includes('\uC18C\uC2A4 \uC5C5\uB85C\uB4DC')) {
							btn.click();
							return { success: true, text: text };
						}
					}
					return { success: false, error: 'Source add button not found' };
				})();
			`);
      console.log("[NotebookLM Bridge] Link Step 1 (\uC18C\uC2A4 \uCD94\uAC00 \uBC84\uD2BC):", step1);
      await this.delay(1500);
      await view.webview.executeJavaScript(`
				(function() {
					const m = document.querySelector('mat-bottom-sheet-container, .upload-dialog-panel');
					if (m) m.scrollTop = m.scrollHeight;
					for (const el of document.querySelectorAll('*')) {
						const text = (el.textContent || '').trim();
						if (text === '\uB9C1\uD06C' || text === '\uC6F9\uC0AC\uC774\uD2B8') {
							el.scrollIntoView({ block: 'center' });
							break;
						}
					}
				})();
			`);
      await this.delay(500);
      const step2 = await view.webview.executeJavaScript(`
				(function() {
					for (const el of document.querySelectorAll('*')) {
						const text = (el.textContent || '').trim();
						if (text === '\uB9C1\uD06C') {
							el.click();
							return { success: true, tag: el.tagName };
						}
					}
					return { success: false, error: '\uB9C1\uD06C option not found' };
				})();
			`);
      console.log("[NotebookLM Bridge] Link Step 2 (\uB9C1\uD06C \uD074\uB9AD):", step2);
      await this.delay(1e3);
      const step3 = await view.webview.executeJavaScript(`
				(function() {
					for (const el of document.querySelectorAll('span, div, button, a')) {
						const text = (el.textContent || '').trim();
						if (text === '\uC6F9\uC0AC\uC774\uD2B8' || text === 'Website') {
							el.click();
							return { success: true, tag: el.tagName };
						}
					}
					return { success: false, error: '\uC6F9\uC0AC\uC774\uD2B8 option not found' };
				})();
			`);
      console.log("[NotebookLM Bridge] Link Step 3 (\uC6F9\uC0AC\uC774\uD2B8 \uD074\uB9AD):", step3);
      await this.delay(2e3);
      const shareLink = note.shareLink;
      const step4 = await view.webview.executeJavaScript(`
				(function() {
					const url = ${JSON.stringify(shareLink)};

					// textarea \uCC3E\uAE30 (\uC6F9\uC0AC\uC774\uD2B8 URL \uB2E4\uC774\uC5BC\uB85C\uADF8)
					const dialogs = document.querySelectorAll('mat-dialog-container, [role="dialog"], .cdk-overlay-pane');
					for (const dialog of dialogs) {
						const text = (dialog.textContent || '');
						if (text.includes('\uC6F9\uC0AC\uC774\uD2B8 URL') || text.includes('URL \uBD99\uC5EC\uB123\uAE30')) {
							const ta = dialog.querySelector('textarea');
							if (ta && ta.offsetParent !== null) {
								ta.focus();
								ta.value = url;
								ta.dispatchEvent(new Event('input', { bubbles: true }));
								ta.dispatchEvent(new Event('change', { bubbles: true }));
								return { success: true, method: 'dialog textarea' };
							}
						}
					}

					// placeholder\uB85C \uCC3E\uAE30
					const textareas = document.querySelectorAll('textarea');
					for (const ta of textareas) {
						const placeholder = (ta.placeholder || '').toLowerCase();
						if (placeholder.includes('url') || placeholder.includes('\uBD99\uC5EC\uB123\uAE30')) {
							if (ta.offsetParent !== null) {
								ta.focus();
								ta.value = url;
								ta.dispatchEvent(new Event('input', { bubbles: true }));
								ta.dispatchEvent(new Event('change', { bubbles: true }));
								return { success: true, method: 'placeholder textarea' };
							}
						}
					}

					// \uC544\uBB34 visible textarea
					for (const ta of textareas) {
						if (ta.offsetParent !== null) {
							ta.focus();
							ta.value = url;
							ta.dispatchEvent(new Event('input', { bubbles: true }));
							ta.dispatchEvent(new Event('change', { bubbles: true }));
							return { success: true, method: 'any visible textarea' };
						}
					}

					return { success: false, error: 'URL textarea not found' };
				})();
			`);
      console.log("[NotebookLM Bridge] Link Step 4 (URL \uC785\uB825):", step4);
      await this.delay(1e3);
      const step5 = await view.webview.executeJavaScript(`
				(function() {
					const buttons = document.querySelectorAll('button');
					for (const btn of buttons) {
						const text = (btn.textContent || '').trim();
						if (text === '\uC0BD\uC785' || text === 'Insert') {
							if (!btn.disabled) {
								btn.click();
								return { success: true };
							} else {
								return { success: false, error: '\uC0BD\uC785 button is disabled' };
							}
						}
					}
					return { success: false, error: '\uC0BD\uC785 button not found' };
				})();
			`);
      console.log("[NotebookLM Bridge] Link Step 5 (\uC0BD\uC785 \uBC84\uD2BC):", step5);
      if ((step4 == null ? void 0 : step4.success) && (step5 == null ? void 0 : step5.success)) {
        new import_obsidian.Notice(`\u2705 "${note.title}" \uB9C1\uD06C \uC18C\uC2A4\uAC00 \uCD94\uAC00\uB418\uC5C8\uC2B5\uB2C8\uB2E4!
(${note.shareLink})`, 5e3);
      } else if (step4 == null ? void 0 : step4.success) {
        new import_obsidian.Notice(`\u{1F4DD} URL \uC785\uB825 \uC644\uB8CC!
"\uC0BD\uC785" \uBC84\uD2BC\uC744 \uD074\uB9AD\uD574\uC8FC\uC138\uC694.`, 5e3);
      } else {
        await navigator.clipboard.writeText(note.shareLink);
        new import_obsidian.Notice(`\u{1F4CB} \uC790\uB3D9 \uC785\uB825 \uC2E4\uD328. URL\uC774 \uD074\uB9BD\uBCF4\uB4DC\uC5D0 \uBCF5\uC0AC\uB428.

${note.shareLink}`, 8e3);
      }
    } catch (error) {
      console.error("[NotebookLM Bridge] Link source add failed:", error);
      try {
        await navigator.clipboard.writeText(note.shareLink);
        new import_obsidian.Notice(`\u{1F4CB} "${note.title}" URL\uC774 \uD074\uB9BD\uBCF4\uB4DC\uC5D0 \uBCF5\uC0AC\uB428.

\uC218\uB3D9\uC73C\uB85C \uBD99\uC5EC\uB123\uAE30 \uD574\uC8FC\uC138\uC694.`, 8e3);
      } catch (e) {
        new import_obsidian.Notice("\uB9C1\uD06C \uC18C\uC2A4 \uCD94\uAC00\uC5D0 \uC2E4\uD328\uD588\uC2B5\uB2C8\uB2E4.", 5e3);
      }
    }
  }
  delay(ms) {
    return new Promise((resolve) => setTimeout(resolve, ms));
  }
  // 디버그: 웹뷰 DOM 정보 수집
  async debugWebviewDOM() {
    const view = this.getNotebookLMView();
    if (!view || !view.webview) {
      new import_obsidian.Notice("NotebookLM \uC6F9\uBDF0\uAC00 \uC5F4\uB824\uC788\uC9C0 \uC54A\uC2B5\uB2C8\uB2E4.\n\uBA3C\uC800 NotebookLM\uC744 \uC5F4\uC5B4\uC8FC\uC138\uC694.");
      return;
    }
    new import_obsidian.Notice("DOM \uC815\uBCF4 \uC218\uC9D1 \uC911...");
    try {
      const domInfo = await view.webview.executeJavaScript(`
				(function() {
					const info = {
						url: window.location.href,
						title: document.title,
						buttons: [],
						clickableElements: [],
						textInputs: [],
						dialogs: [],
						notebookLinks: []
					};

					// \uBAA8\uB4E0 \uBC84\uD2BC \uC815\uBCF4
					document.querySelectorAll('button').forEach((btn, i) => {
						info.buttons.push({
							index: i,
							text: (btn.textContent || '').trim().substring(0, 50),
							ariaLabel: btn.getAttribute('aria-label'),
							className: btn.className.substring(0, 100),
							disabled: btn.disabled,
							visible: btn.offsetParent !== null
						});
					});

					// role="button" \uC694\uC18C\uB4E4
					document.querySelectorAll('[role="button"]').forEach((el, i) => {
						info.clickableElements.push({
							index: i,
							tagName: el.tagName,
							text: (el.textContent || '').trim().substring(0, 50),
							ariaLabel: el.getAttribute('aria-label'),
							className: el.className.substring(0, 100)
						});
					});

					// \uD14D\uC2A4\uD2B8 \uC785\uB825 \uD544\uB4DC
					document.querySelectorAll('textarea, input[type="text"], input:not([type]), [contenteditable="true"]').forEach((el, i) => {
						info.textInputs.push({
							index: i,
							tagName: el.tagName,
							placeholder: el.getAttribute('placeholder'),
							className: el.className.substring(0, 100),
							visible: el.offsetParent !== null
						});
					});

					// \uB2E4\uC774\uC5BC\uB85C\uADF8/\uBAA8\uB2EC
					document.querySelectorAll('[role="dialog"], [role="modal"], [class*="dialog"], [class*="modal"]').forEach((el, i) => {
						info.dialogs.push({
							index: i,
							tagName: el.tagName,
							role: el.getAttribute('role'),
							className: el.className.substring(0, 100),
							visible: el.offsetParent !== null,
							innerText: (el.textContent || '').trim().substring(0, 200)
						});
					});

					// \uB178\uD2B8\uBD81 \uB9C1\uD06C \uC815\uBCF4 \uC218\uC9D1 (a \uD0DC\uADF8)
					document.querySelectorAll('a[href*="/notebook/"]').forEach((el, i) => {
						const href = el.getAttribute('href') || '';
						const parent = el.closest('[class*="card"], [class*="item"], [class*="project"]');
						let title = '';
						if (parent) {
							const titleEl = parent.querySelector('[class*="title"], [class*="name"], h1, h2, h3');
							if (titleEl) title = titleEl.textContent.trim();
						}
						if (!title) title = el.textContent.trim();

						info.notebookLinks.push({
							index: i,
							href: href,
							title: title.substring(0, 100),
							parentClass: parent ? parent.className.substring(0, 100) : null,
							type: 'a-tag'
						});
					});

					// \uD504\uB85C\uC81D\uD2B8/\uB178\uD2B8\uBD81 \uCE74\uB4DC \uC694\uC18C \uC218\uC9D1
					info.projectCards = [];
					document.querySelectorAll('[class*="project-card"], [class*="notebook"], mat-card, [class*="card"]').forEach((el, i) => {
						const text = (el.textContent || '').trim().substring(0, 100);
						const link = el.querySelector('a');
						info.projectCards.push({
							index: i,
							tagName: el.tagName,
							className: el.className.substring(0, 150),
							text: text,
							hasLink: !!link,
							linkHref: link ? link.getAttribute('href') : null
						});
					});

					// \uD074\uB9AD \uAC00\uB2A5\uD55C project \uAD00\uB828 \uC694\uC18C
					info.projectItems = [];
					document.querySelectorAll('[class*="project"]').forEach((el, i) => {
						if (i < 30) { // \uCC98\uC74C 30\uAC1C\uB9CC
							info.projectItems.push({
								index: i,
								tagName: el.tagName,
								className: el.className.substring(0, 150),
								text: (el.textContent || '').trim().substring(0, 80)
							});
						}
					});

					return info;
				})();
			`);
      const debugContent = JSON.stringify(domInfo, null, 2);
      const debugPath = "notebooklm-debug.json";
      await this.app.vault.adapter.write(debugPath, debugContent);
      new import_obsidian.Notice(`DOM \uC815\uBCF4\uAC00 ${debugPath}\uC5D0 \uC800\uC7A5\uB418\uC5C8\uC2B5\uB2C8\uB2E4.

\uBC84\uD2BC ${domInfo.buttons.length}\uAC1C
\uB178\uD2B8\uBD81 \uB9C1\uD06C ${domInfo.notebookLinks.length}\uAC1C
\uC785\uB825\uD544\uB4DC ${domInfo.textInputs.length}\uAC1C
\uB2E4\uC774\uC5BC\uB85C\uADF8 ${domInfo.dialogs.length}\uAC1C`, 8e3);
      console.log("[NotebookLM Bridge] DOM Info:", domInfo);
    } catch (error) {
      console.error("[NotebookLM Bridge] Debug failed:", error);
      new import_obsidian.Notice("DOM \uC815\uBCF4 \uC218\uC9D1 \uC2E4\uD328: " + error.message);
    }
  }
  async sendTextToQueue(text, title) {
    const note = {
      title,
      content: text,
      path: ""
    };
    this.addToQueue(note);
    new import_obsidian.Notice("\uC120\uD0DD\uB41C \uD14D\uC2A4\uD2B8\uAC00 \uB300\uAE30\uC5F4\uC5D0 \uCD94\uAC00\uB418\uC5C8\uC2B5\uB2C8\uB2E4.");
  }
  addToQueue(note) {
    const id = `note-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
    this.noteQueue.set(id, {
      id,
      note,
      timestamp: Date.now(),
      status: "pending"
    });
    this.updateStatusBar();
  }
};
var NotebookLMView = class extends import_obsidian.ItemView {
  // Electron webview
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
  }
  getViewType() {
    return NOTEBOOKLM_VIEW_TYPE;
  }
  getDisplayText() {
    return "NotebookLM";
  }
  getIcon() {
    return "book-open";
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("notebooklm-view-container");
    const toolbar = container.createDiv("notebooklm-toolbar");
    const refreshBtn = toolbar.createEl("button", { text: "\u{1F504} \uC0C8\uB85C\uACE0\uCE68" });
    refreshBtn.onclick = () => this.refresh();
    const listBtn = toolbar.createEl("button", { text: "\u{1F4DA} \uB178\uD2B8\uBD81 \uBAA9\uB85D" });
    listBtn.onclick = () => this.goToNotebookList();
    const addBtn = toolbar.createEl("button", { text: "\u{1F4E5} \uB300\uAE30\uC5F4 \uCD94\uAC00", cls: "mod-cta" });
    addBtn.onclick = () => this.addFromQueue();
    this.webviewEl = container.createDiv("notebooklm-webview-container");
    const webviewHtml = `<webview
			id="notebooklm-webview"
			src="https://notebooklm.google.com"
			style="width: 100%; height: 100%;"
			allowpopups
			partition="persist:notebooklm"
		></webview>`;
    this.webviewEl.innerHTML = webviewHtml;
    this.webview = this.webviewEl.querySelector("webview");
    if (this.webview) {
      this.webview.addEventListener("dom-ready", () => {
        this.injectScript();
      });
      this.webview.addEventListener("ipc-message", (event) => {
        this.handleWebviewMessage(event);
      });
      this.webview.addEventListener("did-navigate", (event) => {
        console.log("[NotebookLM] Navigated to:", event.url);
      });
    }
  }
  async onClose() {
  }
  refresh() {
    if (this.webview) {
      this.webview.reload();
    }
  }
  goToNotebookList() {
    if (this.webview) {
      this.webview.loadURL("https://notebooklm.google.com");
    }
  }
  // 웹뷰에 스크립트 삽입
  async injectScript() {
    if (!this.webview)
      return;
    const script = `
			(function() {
				if (window.__obsidianBridgeInjected) return;
				window.__obsidianBridgeInjected = true;

				console.log('[Obsidian Bridge] Script injected');

				// \uD398\uC774\uC9C0 \uC0C1\uD0DC \uBD84\uC11D
				function analyzePageState() {
					const path = window.location.pathname;
					const state = {
						path: path,
						isNotebookList: path === '/' || path === '',
						isInsideNotebook: path.includes('/notebook/'),
						notebookId: null,
						notebookTitle: null
					};

					if (state.isInsideNotebook) {
						const match = path.match(/\\/notebook\\/([^/]+)/);
						if (match) state.notebookId = match[1];

						// \uB178\uD2B8\uBD81 \uC81C\uBAA9 \uCC3E\uAE30
						const titleEl = document.querySelector('h1, [class*="title"]');
						if (titleEl) state.notebookTitle = titleEl.textContent.trim();
					}

					return state;
				}

				// \uB178\uD2B8\uBD81 \uBAA9\uB85D \uAC00\uC838\uC624\uAE30
				function getNotebookList() {
					const notebooks = [];
					// NotebookLM\uC758 \uB178\uD2B8\uBD81 \uCE74\uB4DC/\uB9C1\uD06C \uCC3E\uAE30
					document.querySelectorAll('a[href*="/notebook/"]').forEach(el => {
						const href = el.getAttribute('href');
						const match = href.match(/\\/notebook\\/([^/]+)/);
						if (match) {
							notebooks.push({
								id: match[1],
								title: el.textContent.trim() || 'Untitled',
								url: href
							});
						}
					});
					return notebooks;
				}

				// \uC18C\uC2A4 \uCD94\uAC00 \uD568\uC218
				async function addSource(content, title) {
					console.log('[Obsidian Bridge] Adding source:', title);

					// "Add source" \uBC84\uD2BC \uCC3E\uAE30
					const addBtnSelectors = [
						'button[aria-label*="Add"]',
						'button[aria-label*="source"]',
						'[class*="add-source"]',
						'button:has(span:contains("Add"))'
					];

					let addBtn = null;
					for (const sel of addBtnSelectors) {
						try {
							addBtn = document.querySelector(sel);
							if (addBtn) break;
						} catch(e) {}
					}

					if (addBtn) {
						addBtn.click();
						await new Promise(r => setTimeout(r, 500));
					}

					// "Copied text" \uC635\uC158 \uCC3E\uAE30
					const textOptionSelectors = [
						'[role="menuitem"]',
						'button',
						'div[class*="option"]'
					];

					for (const sel of textOptionSelectors) {
						const els = document.querySelectorAll(sel);
						for (const el of els) {
							if (el.textContent.includes('Copied text') ||
								el.textContent.includes('Paste') ||
								el.textContent.includes('\uD14D\uC2A4\uD2B8')) {
								el.click();
								await new Promise(r => setTimeout(r, 500));
								break;
							}
						}
					}

					// textarea \uCC3E\uC544\uC11C \uB0B4\uC6A9 \uC785\uB825
					const textarea = document.querySelector('textarea, [contenteditable="true"]');
					if (textarea) {
						const fullContent = '# ' + title + '\\n\\n' + content;
						if (textarea.tagName === 'TEXTAREA') {
							textarea.value = fullContent;
							textarea.dispatchEvent(new Event('input', { bubbles: true }));
						} else {
							textarea.textContent = fullContent;
							textarea.dispatchEvent(new InputEvent('input', { bubbles: true }));
						}
						await new Promise(r => setTimeout(r, 300));

						// \uD655\uC778 \uBC84\uD2BC \uD074\uB9AD
						const confirmBtn = Array.from(document.querySelectorAll('button')).find(
							btn => btn.textContent.includes('Insert') ||
								   btn.textContent.includes('Add') ||
								   btn.textContent.includes('\uCD94\uAC00')
						);
						if (confirmBtn) {
							confirmBtn.click();
							return { success: true };
						}
					}

					// \uC2E4\uD328 \uC2DC \uD074\uB9BD\uBCF4\uB4DC\uC5D0 \uBCF5\uC0AC
					const fullContent = '# ' + title + '\\n\\n' + content;
					await navigator.clipboard.writeText(fullContent);
					return { success: false, clipboard: true };
				}

				// \uBA54\uC2DC\uC9C0 \uB9AC\uC2A4\uB108
				window.addEventListener('message', async (event) => {
					if (event.data.type === 'obsidian-bridge') {
						const { action, payload } = event.data;
						let result = null;

						switch(action) {
							case 'getPageState':
								result = analyzePageState();
								break;
							case 'getNotebooks':
								result = getNotebookList();
								break;
							case 'addSource':
								result = await addSource(payload.content, payload.title);
								break;
							case 'navigateTo':
								window.location.href = payload.url;
								result = { success: true };
								break;
						}

						// \uACB0\uACFC \uC804\uC1A1
						if (window.require) {
							const { ipcRenderer } = window.require('electron');
							ipcRenderer.sendToHost('obsidian-bridge-response', { action, result });
						}
					}
				});

				// \uCD08\uAE30 \uC0C1\uD0DC \uC804\uC1A1
				setTimeout(() => {
					const state = analyzePageState();
					if (window.require) {
						const { ipcRenderer } = window.require('electron');
						ipcRenderer.sendToHost('obsidian-bridge-response', {
							action: 'pageStateChanged',
							result: state
						});
					}
				}, 1000);

				// URL \uBCC0\uACBD \uAC10\uC9C0
				let lastPath = window.location.pathname;
				setInterval(() => {
					if (window.location.pathname !== lastPath) {
						lastPath = window.location.pathname;
						const state = analyzePageState();
						if (window.require) {
							const { ipcRenderer } = window.require('electron');
							ipcRenderer.sendToHost('obsidian-bridge-response', {
								action: 'pageStateChanged',
								result: state
							});
						}
					}
				}, 1000);
			})();
		`;
    try {
      await this.webview.executeJavaScript(script);
      console.log("[NotebookLM] Script injected successfully");
    } catch (error) {
      console.error("[NotebookLM] Script injection failed:", error);
    }
  }
  // 웹뷰로 메시지 보내기
  sendToWebview(action, payload) {
    if (this.webview) {
      this.webview.executeJavaScript(`
				window.postMessage({ type: 'obsidian-bridge', action: '${action}', payload: ${JSON.stringify(payload || {})} }, '*');
			`);
    }
  }
  // 웹뷰 메시지 처리
  handleWebviewMessage(event) {
    const { action, result } = event.args[0] || {};
    console.log("[NotebookLM] Message from webview:", action, result);
    if (action === "pageStateChanged") {
      this.plugin.currentPageState = result;
      this.plugin.updateStatusBar();
    }
  }
  // 대기열에서 노트 추가
  async addFromQueue() {
    var _a;
    const pendingNotes = Array.from(this.plugin.noteQueue.entries()).filter(([, item2]) => item2.status === "pending");
    if (pendingNotes.length === 0) {
      new import_obsidian.Notice("\uB300\uAE30\uC5F4\uC774 \uBE44\uC5B4\uC788\uC2B5\uB2C8\uB2E4");
      return;
    }
    if (!((_a = this.plugin.currentPageState) == null ? void 0 : _a.isInsideNotebook)) {
      new import_obsidian.Notice("\uBA3C\uC800 \uB178\uD2B8\uBD81\uC744 \uC120\uD0DD\uD574\uC8FC\uC138\uC694");
      return;
    }
    const [id, item] = pendingNotes[0];
    new import_obsidian.Notice(`"${item.note.title}" \uCD94\uAC00 \uC911...`);
    this.sendToWebview("addSource", {
      title: item.note.title,
      content: item.note.content
    });
    setTimeout(() => {
      this.plugin.noteQueue.delete(id);
      this.plugin.updateStatusBar();
      new import_obsidian.Notice(`"${item.note.title}" \uCD94\uAC00 \uC644\uB8CC!`);
    }, 2e3);
  }
};
var NotebookSelectModal = class extends import_obsidian.Modal {
  constructor(app, plugin, notebooks, noteTitle, onSelect) {
    super(app);
    this.plugin = plugin;
    this.notebooks = notebooks;
    this.noteTitle = noteTitle;
    this.onSelect = onSelect;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("notebooklm-select-modal");
    contentEl.createEl("h2", { text: "\u{1F4DA} \uB178\uD2B8\uBD81 \uC120\uD0DD" });
    contentEl.createEl("p", {
      text: `"${this.noteTitle}" \uB178\uD2B8\uB97C \uC5B4\uB514\uC5D0 \uCD94\uAC00\uD560\uAE4C\uC694?`,
      cls: "modal-description"
    });
    const newSection = contentEl.createDiv("modal-section");
    newSection.createEl("h3", { text: "\uC0C8 \uB178\uD2B8\uBD81" });
    const newItem = newSection.createDiv("notebook-item new");
    newItem.innerHTML = `
			<span class="notebook-icon">\u2795</span>
			<div class="notebook-info">
				<span class="notebook-title">\uC0C8 \uB178\uD2B8\uBD81 \uB9CC\uB4E4\uAE30</span>
				<span class="notebook-desc">NotebookLM\uC5D0\uC11C \uC0C8 \uB178\uD2B8\uBD81\uC744 \uC0DD\uC131\uD569\uB2C8\uB2E4</span>
			</div>
		`;
    newItem.onclick = () => {
      this.onSelect(null);
      this.close();
    };
    if (this.notebooks.length > 0) {
      const existingSection = contentEl.createDiv("modal-section");
      existingSection.createEl("h3", { text: `\uAE30\uC874 \uB178\uD2B8\uBD81 (${this.notebooks.length}\uAC1C)` });
      const list = existingSection.createDiv("notebook-list");
      this.notebooks.forEach((notebook) => {
        const item = list.createDiv("notebook-item");
        item.innerHTML = `
					<span class="notebook-icon">\u{1F4D3}</span>
					<div class="notebook-info">
						<span class="notebook-title">${notebook.title}</span>
					</div>
				`;
        item.onclick = () => {
          this.onSelect(notebook);
          this.close();
        };
      });
    } else {
      const emptyMsg = contentEl.createDiv("empty-message");
      emptyMsg.innerHTML = `
				<p>\u26A0\uFE0F \uAE30\uC874 \uB178\uD2B8\uBD81\uC744 \uCC3E\uC744 \uC218 \uC5C6\uC2B5\uB2C8\uB2E4.</p>
				<p class="hint">NotebookLM \uC6F9\uBDF0\uC5D0\uC11C \uB178\uD2B8\uBD81 \uBAA9\uB85D \uD398\uC774\uC9C0\uB85C \uC774\uB3D9\uD55C \uD6C4 \uB2E4\uC2DC \uC2DC\uB3C4\uD574\uC8FC\uC138\uC694.</p>
			`;
    }
    const footer = contentEl.createDiv("modal-footer");
    const cancelBtn = footer.createEl("button", { text: "\uCDE8\uC18C" });
    cancelBtn.onclick = () => this.close();
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var NotebookLMBridgeSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "NotebookLM Bridge \uC124\uC815" });
    const statusDiv = containerEl.createDiv("setting-item");
    statusDiv.createEl("div", {
      text: this.plugin.isServerRunning ? "\u{1F7E2} \uC11C\uBC84 \uC2E4\uD589 \uC911" : "\u{1F534} \uC11C\uBC84 \uC911\uC9C0\uB428",
      cls: "setting-item-name"
    });
    new import_obsidian.Setting(containerEl).setName("\uC11C\uBC84 \uD3EC\uD2B8").setDesc("\uBE0C\uB9BF\uC9C0 \uC11C\uBC84\uAC00 \uC0AC\uC6A9\uD560 \uD3EC\uD2B8 \uBC88\uD638 (\uAE30\uBCF8: 27123)").addText((text) => text.setPlaceholder("27123").setValue(this.plugin.settings.serverPort.toString()).onChange(async (value) => {
      const port = parseInt(value);
      if (!isNaN(port) && port > 0 && port < 65536) {
        this.plugin.settings.serverPort = port;
        await this.plugin.saveSettings();
      }
    }));
    new import_obsidian.Setting(containerEl).setName("\uC790\uB3D9 \uC2DC\uC791").setDesc("\uC635\uC2DC\uB514\uC5B8 \uC2DC\uC791 \uC2DC \uBE0C\uB9BF\uC9C0 \uC11C\uBC84 \uC790\uB3D9 \uC2DC\uC791").addToggle((toggle) => toggle.setValue(this.plugin.settings.autoStart).onChange(async (value) => {
      this.plugin.settings.autoStart = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\uBA54\uD0C0\uB370\uC774\uD130 \uD3EC\uD568").setDesc("\uB178\uD2B8 \uC804\uC1A1 \uC2DC \uC0DD\uC131/\uC218\uC815 \uC2DC\uAC04, \uD0DC\uADF8 \uB4F1 \uBA54\uD0C0\uB370\uC774\uD130 \uD3EC\uD568").addToggle((toggle) => toggle.setValue(this.plugin.settings.includeMetadata).onChange(async (value) => {
      this.plugin.settings.includeMetadata = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Frontmatter \uD3EC\uD568").setDesc("\uB178\uD2B8 \uC804\uC1A1 \uC2DC YAML frontmatter \uD3EC\uD568").addToggle((toggle) => toggle.setValue(this.plugin.settings.includeFrontmatter).onChange(async (value) => {
      this.plugin.settings.includeFrontmatter = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\uC11C\uBC84 \uC81C\uC5B4").setDesc("\uBE0C\uB9BF\uC9C0 \uC11C\uBC84 \uC2DC\uC791 \uB610\uB294 \uC911\uC9C0").addButton((button) => button.setButtonText(this.plugin.isServerRunning ? "\uC11C\uBC84 \uC911\uC9C0" : "\uC11C\uBC84 \uC2DC\uC791").onClick(async () => {
      if (this.plugin.isServerRunning) {
        await this.plugin.stopServer();
      } else {
        await this.plugin.startServer();
      }
      this.display();
    }));
    containerEl.createEl("h3", { text: "\uD06C\uB86C \uD655\uC7A5 \uD504\uB85C\uADF8\uB7A8" });
    containerEl.createEl("p", {
      text: "\uC774 \uD50C\uB7EC\uADF8\uC778\uC744 \uC0AC\uC6A9\uD558\uB824\uBA74 \uB3D9\uBC18 \uD06C\uB86C \uD655\uC7A5 \uD504\uB85C\uADF8\uB7A8\uC774 \uD544\uC694\uD569\uB2C8\uB2E4. NotebookLM \uD398\uC774\uC9C0\uC5D0\uC11C \uD06C\uB86C \uD655\uC7A5\uC744 \uD1B5\uD574 \uB300\uAE30\uC5F4\uC758 \uB178\uD2B8\uB97C \uCD94\uAC00\uD560 \uC218 \uC788\uC2B5\uB2C8\uB2E4."
    });
    containerEl.createEl("h3", { text: "API \uC5D4\uB4DC\uD3EC\uC778\uD2B8" });
    const apiList = containerEl.createEl("ul");
    const endpoints = [
      "GET /status - \uC11C\uBC84 \uC0C1\uD0DC \uD655\uC778",
      "GET /current-note - \uD604\uC7AC \uD65C\uC131 \uB178\uD2B8 \uAC00\uC838\uC624\uAE30",
      "GET /queue - \uB300\uAE30\uC5F4 \uC870\uD68C",
      "POST /queue/pop - \uB300\uAE30\uC5F4\uC5D0\uC11C \uB178\uD2B8 \uAC00\uC838\uC624\uAE30",
      "DELETE /queue/clear - \uB300\uAE30\uC5F4 \uBE44\uC6B0\uAE30"
    ];
    endpoints.forEach((ep) => {
      apiList.createEl("li", { text: ep });
    });
  }
};
